### ISSUE TITLE
[TODO] Login/authentication

### ISSUE THREAD

**Issue by KOOKIIEStudios** [BAA-Studios/MOOgiwara#17]
## Abstract
Allow users to log in so that their teams/decks can be saved on the server

## Details
Make use of Google to handle signing in: https://developers.google.com/identity/gsi/web/guides/overview

This way, we do not need to worry about handling and storing of passwords.

## Tasks
- [x] Set up GSI
- [x] Have the user IDs stored in MongoDB database

**Comment by Bratah123** [comment]
![MOOgiwara Relational Model](https://user-images.githubusercontent.com/58405975/223590944-4cfc0936-35ef-438f-8921-8afcc9d09c56.jpg)
![MOOgiwara Database ER Model](https://user-images.githubusercontent.com/58405975/223590949-70c0fce3-afa6-42aa-9174-ba2b7f698f12.jpg)

More information about the database structure.

**Comment by KOOKIIEStudios** [comment]
Prototype (missing notifications for positive feedback) completed as of 11e9e5f
