### ISSUE TITLE
[TODO] Card Database

### ISSUE THREAD

**Issue by Bratah123** [BAA-Studios/MOOgiwara#5]
## Abstract
This task consists of collecting every legal card in Standard in NA and storing it in any data system.

The database should consist of the following:
- card's cost
- attack power
- attribute
- Card effect/description
- Card Image

## Details
Find information on cards here: https://en.onepiece-cardgame.com/cardlist/?series=569101

## Tasks
- [x] Data

**Comment by KOOKIIEStudios** [comment]
Data has been scraped: https://github.com/BAA-Studios/OPTCG-Metadata-Scaper/releases/tag/v1.0.0
Each card is represented as its own JSON file

**Comment by KOOKIIEStudios** [comment]
AIO JSON file, as previously requested: https://github.com/BAA-Studios/OPTCG-Metadata-Scaper/releases/download/v1.0.1/metadata.json
