### ISSUE TITLE
[BUG]  when opponent is attacking me , there is no where i can clcik

### ISSUE THREAD

**Issue by anson1788** [BAA-Studios/MOOgiwara#74]
Not sure if this is a bug , when opponent is attacking me , there is no where i can clcik 
<img width="1410" alt="Screenshot 2023-06-10 at 11 57 23 PM" src="https://github.com/BAA-Studios/MOOgiwara/assets/23080221/139ce30b-06ce-4ea7-acbc-41cb6f74f7bd">

**Comment by Bratah123** [comment]
This is technically "intentional" because I've never gotten to finish the code that completes this phase of the game.
Refer to issue #42
